import io
from fpdf import FPDF


def generate_keys_pdf(username: str, keys: dict) -> bytes:
    """Generate a PDF containing Steem account credentials. Returns bytes."""
    pdf = FPDF()
    pdf.add_page()
    pdf.set_margins(20, 20, 20)

    # Title
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 12, "Steem Account Credentials", ln=True, align="C")
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 13)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 8, f"Account: @{username}", ln=True, align="C")
    pdf.ln(8)

    # Warning box
    pdf.set_fill_color(255, 230, 230)
    pdf.set_draw_color(200, 0, 0)
    pdf.set_line_width(0.5)
    pdf.rect(20, pdf.get_y(), 170, 22, style="DF")
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(180, 0, 0)
    pdf.set_xy(22, pdf.get_y() + 3)
    pdf.multi_cell(166, 5,
        "WARNING: Store these keys securely and offline. Anyone with these keys has full "
        "access to your account. These keys will NOT be shown again.", align="L")
    pdf.ln(12)

    # Keys
    fields = [
        ("Master Password", keys["master_password"]),
        ("Owner Key (private)", keys["owner_key"]),
        ("Active Key (private)", keys["active_key"]),
        ("Posting Key (private)", keys["posting_key"]),
        ("Memo Key (private)", keys["memo_key"]),
    ]

    for label, value in fields:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 7, label, ln=True)
        pdf.set_font("Courier", "", 9)
        pdf.set_text_color(0, 80, 160)
        pdf.set_fill_color(245, 245, 255)
        pdf.rect(20, pdf.get_y(), 170, 8, style="F")
        pdf.set_xy(22, pdf.get_y() + 1)
        pdf.cell(166, 6, value, ln=True)
        pdf.ln(3)

    # Footer
    pdf.set_y(-30)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 5, "Generated by join.cur8.fun — Keep this document private", align="C", ln=True)

    return bytes(pdf.output())


def generate_keys_txt(username: str, keys: dict) -> str:
    lines = [
        "=== STEEM ACCOUNT CREDENTIALS ===",
        f"Account: @{username}",
        "",
        "WARNING: Store these keys securely and offline.",
        "Anyone with these keys has full access to your account.",
        "These keys will NOT be shown again.",
        "",
        f"Master Password : {keys['master_password']}",
        f"Owner Key       : {keys['owner_key']}",
        f"Active Key      : {keys['active_key']}",
        f"Posting Key     : {keys['posting_key']}",
        f"Memo Key        : {keys['memo_key']}",
        "",
        "Generated by join.cur8.fun",
    ]
    return "\n".join(lines)
